version: '3'

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local


services:
  postgres:
    image: 'postgres:16.1'
    container_name: 'database'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=MonkeyCloud
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
  app:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/MonkeyCloud
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
      - minio
    container_name: 'backend'
    ports:
      - 8080:8080

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio