server:
  port: 8080
  servlet:
    context-path:
jwt:
  secret: fcdjibvjnq42918y093456189435h0ng015g
  lifetime: 120m
spring:
  dataSource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MonkeyCloud
    username: postgres
    password: admin
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
  minio:
    url: http://localhost:9000
    accessKey: admin
    secretKey: password


