server:
  port: 8080
  servlet:
    context-path:
jwt:
  secret: fcdjibvjnq42918y093456189435h0ng015g
  lifetime: 120m
spring:
  config:
    import: optional:file:.env[.properties]
  dataSource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB


